/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Button: typeof import('./components/Form/Button/Button.vue')['default']
    Cadastro: typeof import('./components/Cadastro.vue')['default']
    CadastroAluno: typeof import('./components/CadastroAluno.vue')['default']
    Card: typeof import('./components/Form/Card.vue')['default']
    CardTable: typeof import('./components/Card/CardTable.vue')['default']
    DefaultInput: typeof import('./components/Form/DefaultInput.vue')['default']
    Dialog: typeof import('./components/Dialog/Dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table/Table.vue')['default']
    TitleCard: typeof import('./components/Form/TitleCard.vue')['default']
  }
}
